version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - moodle
      - wordpress
      - word-mastermind
    networks:
      - tarea3

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8080:8080"
    networks:
      - tarea3

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8081:80"
    networks:
      - tarea3

  word-mastermind:
    build: ./word-mastermind
    container_name: word-mastermind
    ports:
      - "8082:80"
    networks:
      - tarea3

  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
    networks:
      - tarea3
    volumes:
      - /tmp/mariadb:/tmp/mariadb

networks:
  tarea3:
    driver: bridge
